name: Ruby

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install Yarn
        run: yarn --frozen-lockfile
      - name: Create Evaluation File
        run: |
          rm -rf spec
          git clone https://github.com/timeshiftseiya/cdp_web_manyo_evaluation_code_debug.git spec
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Create Feedback at Step1
        if: contains(github.ref, 'step1')
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/manyo_test"
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec -r ./spec/my_formatter.rb -f MyFormatter spec/system/step1_spec.rb -o .github/feedback_template.md
        continue-on-error: true

      - name: Rspec Results at Step1
        if: contains(github.ref, 'step1')
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/manyo_test"
        run: |
          bundle exec rspec spec/system/step1_spec.rb
        continue-on-error: true
      - uses: JasonEtco/create-an-issue@v2
        if: contains(github.ref, 'step1') || contains(github.ref, 'step2') || contains(github.ref, 'step3') || contains(github.ref, 'step4') || contains(github.ref, 'step5')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/feedback_template.md